version: '3.8'

services:
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress_data:/var/www/html
      - .wordpress/wp-content/plugins:/var/www/html/wp-content/plugins 

  db:
    image: mysql:8.0
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: examplepass
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    volumes:
      - db_data:/var/lib/mysql

  # Nuxt frontend
  nuxt:
    build:
      context: .
    image: node:18
    container_name: nuxt
    restart: always
    ports:
      - "3000:3000" # Nuxt available on localhost:3000
    volumes:
      - .:/app # Map the root directory for Nuxt
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    depends_on:
      - wordpress

volumes:
  wordpress_data:
  db_data:


